### ISSUE TITLE
Getting java.io.InvalidClassException: com.microsoft.kusto.spark.datasink.SinkTableCreationMode$

### ISSUE THREAD

**Issue by lohithrvce** [Azure/azure-kusto-spark#164]
Hi Team,

We are using  "com.microsoft.kusto.spark.datasink.KustoSinkOptions" library in our spark scala code to write the data into adx  table. We are getting below error from last four days. Please help us to know what could be the issue for this exception.

"Caused by: java.io.InvalidClassException: com.microsoft.kusto.spark.datasink.SinkTableCreationMode$; local class incompatible: stream classdesc serialVersionUID = -8994901548193566197, local class serialVersionUID = -5675826937088959115"

Spark Code : readDf.write.format("com.microsoft.kusto.spark.datasource")
               .option(KustoSinkOptions.KUSTO_CLUSTER, cluster)
               .option(KustoSinkOptions.KUSTO_DATABASE, database)
               .option(KustoSinkOptions.KUSTO_TABLE, temp_table)
               .option(KustoSinkOptions.KUSTO_AAD_APP_ID, appId)
               .option(KustoSinkOptions.KUSTO_AAD_APP_SECRET, appKey)
               .option(KustoSinkOptions.KUSTO_AAD_AUTHORITY_ID, authorityId)
               .option(KustoSinkOptions.KUSTO_TABLE_CREATE_OPTIONS, "CreateIfNotExist")
               .mode(SaveMode.Append)
               .save()

Library : com.microsoft.azure.kusto:kusto-spark_3.0_2.12:2.3.0

Thanks,
Lohith R

**Comment by ohadbitt** [comment]
Please provide the details of the databricks cluster you were using (its version and such)
Usually InvalidClassException is a result of incompatible scala version.  This library version is using spark 2.4 scala 2.11.

Anyway:
Starting version 2.3.0 we introduce new artifact Ids: kusto-spark_3.x_2.12 targeting Spark 3.x and Scala 2.12 and kusto-spark_2.4_2.11 targeting Spark 2.4.x and scala 2.11. For Scala/Java applications using Maven project definitions, link your application with the artifact below in order to use the Azure Data Explorer connector for Spark.

**Comment by ohadbitt** [comment]
Closed for no response
