### ISSUE TITLE
Ingest data into the source table of a materialized view

### ISSUE THREAD

**Issue by rbushri** [Azure/azure-kusto-spark#218]
I created a table Test + materialized view TestMV in order to deduplicate records in the Test table.

I tried to ingest data into the Test table using spark but I got an error: 
"An admin command cannot be executed due to an invalid state: State='Cannot move extents to 'Test' since materialized view 'TestMV' will not process these extents (can lead to data loss in the materialized view)"

According to ADX docs:

```
 The source table of a materialized view:
 
- Must be a table that is being ingested to directly, either using one of the ingestion methods, using an update policy, 
   or ingest from query commands.
  - Specifically, using move extents from other tables into the source table of the materialized view
    is not supported. Move extents may fail with the following error: Cannot drop/move extents from/to table
    'TableName' since Materialized View 'ViewName' is currently processing some of these extents.
```

https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-create#materialized-views-limitations-and-known-issues

The code:

```
df.write
      .format("com.microsoft.kusto.spark.datasource")
      .option(KustoSinkOptions.KUSTO_CLUSTER, cluster)
      .option(KustoSinkOptions.KUSTO_DATABASE, database)
      .option(KustoSinkOptions.KUSTO_TABLE, "Test")
      .option(KustoSinkOptions.KUSTO_AAD_APP_ID, appId)
      .option(KustoSinkOptions.KUSTO_AAD_APP_SECRET, appKey)
      .option(KustoSinkOptions.KUSTO_AAD_AUTHORITY_ID, authorityId)
      .option(KustoSinkOptions.KUSTO_WRITE_ENABLE_ASYNC, true)
      .mode(SaveMode.Append)
      .save()
```

Do you have any idea how to ingest data into the source table of a materialized view using spark?

**Comment by yogilad** [comment]
Due to technical limitations this is currently not supported.
We are working on allowing it in the next releases.

In the meantime you can overcome this by defining an intermediate table with 0 days retention policy, push the data to this table and create an update policy which moves it to the materialized view 
Spark (pushes data to)=> Intermediate Table (update policy)=> Materialized View.

The zero retention policy means nothing is actually saved, and the update policy will make sure the materialized view is updated.
Make sure to set the update policy to be transactional so storing data is considered successful only if it actually landed in the materialized view table.
